name: py36
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - anaconda
  - pytest-cov
  - pytest-xdist
  - coverage
  - flake8
  - pip:
    - argh
    - better-apidoc>=0.1.4
    - livereload
    - pathtools
    - port-for
    - pyx>=0.14.1
    - requests-toolbelt
    - sphinx-autobuild
    - tables
    - tqdm
    - twine
    - watchdog
